// import React, { ReactNode } from 'react';
// import { Inter } from 'next/font/google';
// import './globals.css';
// import Header from '../app/components/header/Header';
// import Footer from './components/footer/Footer';


// const inter = Inter({ subsets: ['latin'] });

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

// interface RootLayoutProps {
//   children: ReactNode;
// }

// export default function RootLayout({ children }: RootLayoutProps) {
//   return (
    
//     <html lang="en">
//       <body className={inter.className}>
//         <Header />
//         {children}
//         <Footer />
//       </body>
//     </html>
//   );
// }

'use client';

import React, { ReactNode } from 'react';
import { Inter } from 'next/font/google';
import './globals.css';
import Header from '../app/components/header/Header';
import Footer from './components/footer/Footer';
import { HelmetProvider } from 'react-helmet-async'; 

interface RootLayoutProps {
  children: ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <HelmetProvider>
      <html lang="en">
        <body >
          <Header />
          {children}
          <Footer />
        </body>
      </html>
    </HelmetProvider>
  );
}
